@include('header')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 sidebar-container">
            {{-- SideBar --}}
            @include('admin.parts.sidebar')
        </div>
        {{-- Page Content --}}
        <div class="col-md-9">
            <h1 class="text-center p-5">
                Registered Attendances List 
            </h1>
            <div class="p-2" id="report" style="border: 2px solid #ccc">
                <div class="row">
                    <div class="col-4">
                        <h2>Perfect GYM Club</h2>
                        <div>
                            <span>5021 Wetzel Lane, Williamsburg</span>
                        </div>
                        <div>
                            <span>Tel: 231-267-6011</span>
                        </div>
                        <div>
                            <span>Email: support@perfectgym.com</span>
                        </div>
                    </div>

                    <div class="col-8">
                        <div>
                            <table class="table table-hover table-bordered text-center" style="font-size: 14px">
                                <thead class="active">
                                    <tr>
                                        <th>Membership ID</th>
                                        <th>Services Taken</th>
                                        <th>My Plans (Upto)</th>
                                        <th>Address</th>
                                        <th>Charge</th>
                                        <th>Attendance Count</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="col">PGC-SS-{{$member->id}}</th>
                                        <th scope="col">{{$member->services}}</th>
                                        <th scope="col">{{$member->plan}} Month/s</th>
                                        <th scope="col">{{$member->address}}</th>
                                        <th scope="col">{{$member->amount}}</th>
                                        <th scope="col">{{$member->attendance_count}}</th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="text-center p-3" style="border: 1px solid #ccc" >
                            <h4>Last Payment Done: </h4>
                            <span>Member Since: {{$member->reg_date}}</span>
                        </div>
                    </div>
                </div>

                <div class="row pt-4">
                    <div class="col-4">
                        <h4 class="p-2">Member {{$member->name}},</h4>
                        <span>Membership is currently {{$member->status}}</span>
                        <div>
                            Thank you for choosing our services.
                        </div>
                        <div>
                            - on the behalf of whole team
                        </div>
                    </div>
                    <div class="col-6"></div>
                    <div class="col-2">
                        <div><h5>Approved By:</h5></div>
                        <div><img src="/imgs/stamp-sample.png" alt="stamp" width="100" height="100"></div>
                        <div><span>Note:AutoGenerated</span></div>
                    </div>
                </div>
            </div>
            <div class="text-center p-3">
                <button class="btn btn-primary" id="btn-print" onclick="window.print()">Print</button>
            </div>
        </div>
    </div>
</div>
@include("footer")