@include('header')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 sidebar-container">
            {{-- SideBar --}}
            @include('admin.parts.sidebar')
        </div>
        {{-- Page Content --}}
        <div class="col-md-9">
            <h1 class="text-center p-5">
                Member Progress Report 
            </h1>
            <div class="p-2" id="report" style="border: 2px solid #ccc">
                <div class="row">
                    <div class="col-4">
                        <h2>Perfect GYM Club</h2>
                        <div>
                            <span>5021 Wetzel Lane, Williamsburg</span>
                        </div>
                        <div>
                            <span>Tel: 231-267-6011</span>
                        </div>
                        <div>
                            <span>Email: support@perfectgym.com</span>
                        </div>
                    </div>

                    <div class="col-8">
                        <div>
                            <table class="table table-hover table-bordered text-center" style="font-size: 14px">
                                <thead class="active">
                                    <tr>
                                        <th>Membership ID</th>
                                        <th>Initial Weight</th>
                                        <th>Current Weight</th>
                                        <th>Services Taken</th>
                                        <th>Plan (Upto)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="col">PGC-SS-{{$member->id}}</th>
                                        <th scope="col">{{$member->ini_weight}} Kg</th>
                                        <th scope="col">{{$member->curr_weight}} Kg</th>
                                        <th scope="col">{{$member->services}}</th>
                                        <th scope="col">{{$member->plan}} Month/s</th>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="text-center p-3" style="border: 1px solid #ccc;font-weight:bold;" >
                            <div>
                                {{$member->name}}'s Body Structure stated as from {{$member->ini_body_type}} to {{$member->curr_body_type}}.
                            </div>
                            <div>
                                With Total Weight Differences of {{$member->ini_weight - $member->curr_weight}} KG
                            </div>
                            As per records of <? date("H")?>
                        </div>
                    </div>
                </div>

                <div class="row pt-4">
                    <div class="col-4">
                        <h4 class="p-2">GYM Member: {{$member->name}},</h4>
                        <span>Weight Variation of {{intval(($member->ini_weight - $member->curr_weight) / $member->ini_weight * 100)}}% as per current updates!</span>
                        <div>
                            Thank you for choosing our services.
                        </div>
                        <div>
                            - on the behalf of whole team
                        </div>
                    </div>
                    <div class="col-6"></div>
                    <div class="col-2">
                        <div><h5>Approved By:</h5></div>
                        <div><img src="/imgs/stamp-sample.png" alt="stamp" width="100" height="100"></div>
                        <div><span>Note:AutoGenerated</span></div>
                    </div>
                </div>
            </div>
            <div class="text-center p-3">
                <button class="btn btn-primary" id="print-btn" onclick="window.print()">Print</button>
            </div>
        </div>
    </div>
</div>
@include("footer")